// Sample global city data for the in-memory repository (dev + tests only).
// Deliberately spans multiple continents/countries/currencies/timezones —
// GlobeTrotter is not built around any single country.
module.exports = [
  {
    name: 'Paris',
    country: 'France',
    countryCode: 'FR',
    region: 'Europe',
    latitude: 48.8566,
    longitude: 2.3522,
    timezone: 'Europe/Paris',
    description: 'The capital of France, known for art, fashion, and cuisine.',
    imageUrl: 'https://images.globetrotter.example/cities/paris.jpg',
  },
  {
    name: 'Tokyo',
    country: 'Japan',
    countryCode: 'JP',
    region: 'Asia',
    latitude: 35.6762,
    longitude: 139.6503,
    timezone: 'Asia/Tokyo',
    description: "Japan's bustling capital, blending ultramodern and traditional.",
    imageUrl: 'https://images.globetrotter.example/cities/tokyo.jpg',
  },
  {
    name: 'New York',
    country: 'United States',
    countryCode: 'US',
    region: 'North America',
    latitude: 40.7128,
    longitude: -74.006,
    timezone: 'America/New_York',
    description: 'A global hub for finance, culture, and entertainment.',
    imageUrl: 'https://images.globetrotter.example/cities/new-york.jpg',
  },
  {
    name: 'Cairo',
    country: 'Egypt',
    countryCode: 'EG',
    region: 'Africa',
    latitude: 30.0444,
    longitude: 31.2357,
    timezone: 'Africa/Cairo',
    description: 'Home to the ancient pyramids of Giza and a vibrant metropolis.',
    imageUrl: 'https://images.globetrotter.example/cities/cairo.jpg',
  },
  {
    name: 'Sydney',
    country: 'Australia',
    countryCode: 'AU',
    region: 'Oceania',
    latitude: -33.8688,
    longitude: 151.2093,
    timezone: 'Australia/Sydney',
    description: 'Iconic harbour city famous for its Opera House.',
    imageUrl: 'https://images.globetrotter.example/cities/sydney.jpg',
  },
  {
    name: 'Rio de Janeiro',
    country: 'Brazil',
    countryCode: 'BR',
    region: 'South America',
    latitude: -22.9068,
    longitude: -43.1729,
    timezone: 'America/Sao_Paulo',
    description: 'Famous for its beaches, Christ the Redeemer, and Carnival.',
    imageUrl: 'https://images.globetrotter.example/cities/rio-de-janeiro.jpg',
  },
  {
    name: 'Bangkok',
    country: 'Thailand',
    countryCode: 'TH',
    region: 'Asia',
    latitude: 13.7563,
    longitude: 100.5018,
    timezone: 'Asia/Bangkok',
    description: 'A vibrant city known for ornate shrines and street life.',
    imageUrl: 'https://images.globetrotter.example/cities/bangkok.jpg',
  },
  {
    name: 'London',
    country: 'United Kingdom',
    countryCode: 'GB',
    region: 'Europe',
    latitude: 51.5072,
    longitude: -0.1276,
    timezone: 'Europe/London',
    description: 'A global city steeped in history and modern culture.',
    imageUrl: 'https://images.globetrotter.example/cities/london.jpg',
  },
  {
    name: 'Nairobi',
    country: 'Kenya',
    countryCode: 'KE',
    region: 'Africa',
    latitude: -1.2921,
    longitude: 36.8219,
    timezone: 'Africa/Nairobi',
    description: 'Gateway to East African safaris and a growing tech hub.',
    imageUrl: 'https://images.globetrotter.example/cities/nairobi.jpg',
  },
  {
    name: 'Dubai',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    region: 'Middle East',
    latitude: 25.2048,
    longitude: 55.2708,
    timezone: 'Asia/Dubai',
    description: 'A futuristic desert metropolis known for luxury and architecture.',
    imageUrl: 'https://images.globetrotter.example/cities/dubai.jpg',
  },
];
